# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_hash', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_hash', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='easy_thumbnails.Source')),
            ],
        ),
        migrations.CreateModel(
            name='ThumbnailDimensions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.PositiveIntegerField(null=True)),
                ('height', models.PositiveIntegerField(null=True)),
                ('thumbnail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='easy_thumbnails.Thumbnail')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together=set([('storage_hash', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='thumbnail',
            unique_together=set([('storage_hash', 'name', 'source')]),
        ),
    ]
